### ISSUE TITLE
Which tokenizer was used?

### ISSUE THREAD

**Issue by lzfelix** [emorynlp/emotion-detection#1]
Hello,

Thank you very much for making this dataset publicly with such ease of use. I would like to know which tokenizer was used to preprocess the transcriptions.

Thank you very much,
Luiz Felix

**Comment by jdchoi77** [comment]
We used the tokenizer in [NLP4J](https://emorynlp.github.io/nlp4j/) and manually fixed quite a few errors.  A python version of the tokenizer can be found from our [ELIT](https://github.com/elitcloud/elit/blob/develop/elit/tokenizer.py) project as well.

**Comment by lzfelix** [comment]
Thank you I think that this issue could be closed by now.
